# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src"
      dockerfile: "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src\\Services\\\
        Basket\\Basket.API\\Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "basketapi:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "C:\\Users\\Legion\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src\\Services\\Basket\\Basket.API:/app:rw"
    - "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src:/src:rw"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.5\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\Installations\\Rider223_000\\\
      bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_28_01_20_30:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src"
      dockerfile: "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src\\Services\\\
        Catalog\\Catalog.API\\Dockerfile"
      target: "build"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57004:57100"
    - "127.0.0.1:57204:57300"
    volumes:
    - "C:\\Users\\Legion\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src\\Services\\Catalog\\\
      Catalog.API:/app:rw"
    - "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src:/src:rw"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.5\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\Installations\\Rider223_000\\\
      bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_28_01_20_30:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src"
      dockerfile: "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src\\Services\\\
        Discount\\Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "discountgrpc:dev"
    ports:
    - "127.0.0.1:57005:57100"
    - "127.0.0.1:57205:57300"
    volumes:
    - "C:\\Users\\Legion\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src\\Services\\Discount:/app:rw"
    - "C:\\Users\\Legion\\Desktop\\microservices_CSharp\\src:/src:rw"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.5\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\Installations\\Rider223_000\\\
      bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Legion\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_28_01_20_30:/var/opt/rider-debugger:rw"
    working_dir: "/app"
